# Stage 1: Builder
FROM golang:1.23-alpine AS builder
WORKDIR /app

# Устанавливаем git для загрузки зависимостей
RUN apk add --no-cache git

# Копируем файлы модулей
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o loadtest ./cmd/loadtest

FROM alpine:latest
WORKDIR /app

RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY --from=builder /app/loadtest /app/loadtest

EXPOSE 8080
ENTRYPOINT ["/app/loadtest"]