version: "3.8"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - appnet

  mock:
    build:
      context: .
      dockerfile: Dockerfile_mock
    ports:
      - "8081:8081"
    networks:
      - appnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - appnet
  loadtest:
    build:
      context: .
      dockerfile: Dockerfile_loadtest
    depends_on:
      - service
    environment:
      - TARGET_URL=http://service:8080/api/v1/measure
      - NEED_TEST=true
    networks:
      - appnet
    tty: true
    stdin_open: true

networks:
  appnet:
    driver: bridge