FROM golang:1.23-alpine AS builder
WORKDIR /app

RUN apk update && apk upgrade


RUN apk add --no-cache git

RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN adduser -D appuser
USER appuser

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o mock ./cmd/mock

FROM alpine:latest
WORKDIR /app

RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY --from=builder /app/mock /app/mock

EXPOSE 8080
ENTRYPOINT ["/app/mock"]